### ISSUE TITLE
Parse Error: syntax error, unexpected ',' (line 99 of <file>)

### ISSUE THREAD

**Issue by Levitas** [wanze/TemplateEngineTwig#8] opened 2017-03-27 08:46 UTC
Hello there,

I get the error from above.

The templates are okay, if i delete the cache and reload the page everything works fine, after the next refresh of the page this error appears.

The file has on the specified line the following content.
/*     {% include "shared/_header.twig" %}*/

So this cannot be the problem.

I´m using
- ProcessWire 3.0.42
- TemplateEngineFactory 1.1.1
- TemplateEngineTwig 1.0.4

any suggestion how to fix this issue?

**Comment by Levitas** [comment] 2017-03-27 09:38
When using ProcessWire ProcessWire 2.7.3 © 2017
it works fine

**Comment by wanze** [comment] 2017-06-13 19:39
Hi @Levitas 
Sorry for my late response, do you still see this issue if you update ProcessWire to the latest 3.0.x?
I'm using the twig engine for my latest project which runs on ProcessWire 3.0.53 and everything works fine. But I guess that the problem is the FileCompiler of ProcessWire which somehow also compiles the compiled twig templates. There were similar issues as yours. However, those should be fixed. I'm also using includes in my twig template and I don't see that problem.

Cheers

**Closed** 2018-03-19 19:07 UTC
